version: '3.8'

services:
  yellow-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yellow-app
    ports:
      - "8001:80"
    networks:
      - mesh

networks:
  mesh:
    external: true
